import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { categoryFiles, loadQuestionBank } from '../server/questions.js';
import { studyBank } from '../server/study-curriculum.js';

const write = process.argv.includes('--write');
const counts = Object.fromEntries(Object.keys(categoryFiles).map(category => [category, loadQuestionBank(category).questions.length]));
const assetPath = 'public/play/assets/question-catalog.js';
const asset = `// Generated by npm run questions:catalog. Counts only; no answer keys.\nwindow.GEEK_QUESTION_COUNTS = Object.freeze(${JSON.stringify(counts, null, 2)});\n`;
let html = readFileSync('public/play/index.html', 'utf8');
for (const [category, count] of Object.entries(counts)) {
  const expression = new RegExp(`(data-category-key="${category}"><strong>[^<]+</strong><span>)[^<]+(</span>)`);
  assert.ok(expression.test(html), category);
  html = html.replace(expression, `$1${count.toLocaleString('en-US')}${category === 'kaspa' ? ' · sourced' : ''}$2`);
}
html = html.replace(/(<span data-mode-detail>)[^<]+(<\/span>)/, `$1${counts.kaspa} distinct Kaspa questions$2`);
const studyPath = 'public/study/index.html';
const study = readFileSync(studyPath, 'utf8').replace(/(<strong data-explored>)0 \/ \d+(<\/strong>)/, `$10 / ${studyBank().length}$2`);
const sourcesPath = 'public/play/sources/index.html';
const sources = readFileSync(sourcesPath, 'utf8')
  .replace(/(<strong data-total-questions>)\d[\d,]*(<\/strong>)/, `$1${Object.values(counts).reduce((a, b) => a + b, 0).toLocaleString('en-US')}$2`)
  .replace(/(<span data-kaspa-count>)\d+(<\/span>)/, `$1${counts.kaspa}$2`)
  .replace(/(<span data-study-count>)\d+(<\/span>)/, `$1${studyBank().length}$2`);
for (const [path, content] of [[assetPath, asset], ['public/play/index.html', html], [studyPath, study], [sourcesPath, sources]]) {
  if (write) writeFileSync(path, content);
  else assert.equal(readFileSync(path, 'utf8'), content, `${path}: run npm run questions:catalog`);
}
console.log(`Question catalog ${write ? 'generated' : 'verified'}: ${Object.values(counts).reduce((a, b) => a + b, 0)} distinct questions.`);
